### ISSUE TITLE
Where can I import convertSchema?

### ISSUE THREAD

**Issue by christopher-caldwell** [stepci/garph#47]
At the README, near the bottom, it mentions you can build your schema with `convertSchema`, but I can't seem to find that function anywhere.

Also, I believe there's a typo right above it, with `buildSchema`

![Screen Shot 2023-03-22 at 5 20 38 PM](https://user-images.githubusercontent.com/62559469/227051594-c5ae4885-a0b6-4afb-a8da-3a554abf6e56.png)

**Comment by christopher-caldwell** [comment]
Ahh, my bad. It's available from `'garph/dist/converter'`.

I think the typo is still valid tho.

**Comment by mishushakov** [comment]
Hey,
Indeed, there was a typo in the docs and `convertSchema` method also does not exist anymore

I'm currently working on the new documentation for Garph, it will make things more clearer and up-to-date
