### ISSUE TITLE
Small details in example schema implementation

### ISSUE THREAD

**Issue by captbaritone** [stepci/garph#57]
I was looking at your example in the readme and noticed a few issues:

1. You specify a description for the `greet` field, but it is not shown in the `Produces the following GraphQL schema` code below. Assuming the description is preserved, it would be cool to show that!

This second one is a bit more pedantic (feel free to ignore!).

The `name` argument is specified as optional, but it is used as if it were non-optional.

The current implementation would take a query

```graphql
query {
  greet
}
```

And return

```json
{
  "greet": "Hello, null"
}
```

**Comment by mishushakov** [comment]
Ahh yes! You're correct.

The name argument is optional but has a default value (Max). Does it count?

Thanks for checking garph out! We'd really appreciate if you could leave a star if you haven't already 😄

**Comment by captbaritone** [comment]
Ah, you're right, I missed the default!
