### ISSUE TITLE
Use Pothos as a GraphQL builder

### ISSUE THREAD

**Issue by ChromeGG** [stepci/garph#60]
Hi!

I discovered you this morning, great idea with GQL and tRPC-like experience!

I briefly reviewed the project. I know it's in a very early stage and much functionality will be added later.  Maybe there is a way to accelerate it by using [Pothos](https://pothos-graphql.dev/) as a query builder? It has numerous useful plugins ([prisma integration](https://pothos-graphql.dev/docs/plugins/prisma), [errors as types](https://pothos-graphql.dev/docs/plugins/errors) and [more](https://pothos-graphql.dev/docs/plugins)). I miss these features in this project a lot. Also, it's battle-tested with many examples. Would be nice to have it there.

If this is completely absurd, sorry for the trouble, I'm not an expert 😄

**Comment by mishushakov** [comment]
We were evaluating Pothos for this project initially, but its type-system wasn't flexible enough for us to go any further.
