### ISSUE TITLE
Dedicated support for loaders

### ISSUE THREAD

**Issue by lorefnon** [stepci/garph#66]
Thank you for creating this library. The API for defining schemas is really nice. 

I am curious if you'd be interested in supporting batch loaders at the framework level similar to mercurius or quarkus. 

Having batching supported at framework level reduces quite a bit of boilerplate around the usual dance of defining data loaders, attaching them to context & later using them in actual resolver. 

Drawing inspiration from [mercurius loaders](https://github.com/mercurius-js/mercurius/blob/master/docs/loaders.md), I'd imagine we could have something like: 

```ts
const batchResolvers: InferBatchResolvers<
  { Query: typeof queryType; },
  {}
> = {
  Query: {
    greet: (queries, context) => queries.map(({ parent, args, info }) => `Hello, ${args.name}`),
  },
};

export const schema = buildSchema({ g, batchResolvers });
```

So a batch resolver is similar to a normal resolver except it receives an array of queries rather than a single query.

**Comment by mishushakov** [comment]
Interesting Idea. We will see what we can do 😄

**Comment by mishushakov** [comment]
I just came up with this idea:

```ts
const resolvers = {
  Dog: {
    name() {
      return "Apollo";
    },
    owner: {
      load: function (batch, args, context, info) {
        return batch.map(({ obj, params }) => obj.name);
      },
    },
  },
};
```

Essentially, you can now return an object with a `load`, which works similarly to mercurius. One benefit of this approach though is that your loaders don't have to be separated from your resolvers

**Comment by lorefnon** [comment]
I think this would be a great addition. 

Minor suggestion is that we generally allow the resolver to be object which can have either a `load` function (without batching) or a `loadBatch` function (with batching). That may be more intuitive from a user's perspective.

**Comment by mishushakov** [comment]
Does the `load` function work like the regular the resolver function then?

**Comment by lorefnon** [comment]
yes, that was my suggestion.

**Comment by mishushakov** [comment]
Added loaders to garph (v0.5.6)

Docs: https://garph.dev/docs/guide/loaders.html

**Comment by lorefnon** [comment]
This is awesome. thank you.

**Comment by harish-github35** [comment]
@lorefnon can you help me with how to call loadbatch using async await, or any reference for loadbatch usage like real db calls

**Comment by lorefnon** [comment]
@harish-github35 You can take a look at [this gist](https://gist.github.com/lorefnon/67a0c14291597cbd6e4a5494a3052daf). The example uses kysely, but you can adapt it for whatever ORM you use. 

While the example works fine, there is a minor issue with types that will be  fixed by https://github.com/stepci/garph/pull/87
