### ISSUE TITLE
Using garph's inbuilt relay schema builder types results in type errors.

### ISSUE THREAD

**Issue by xoldyckk** [stepci/garph#79]
Here's a codesandbox link:- https://codesandbox.io/p/sandbox/quizzical-wood-66llf3

Check out the index.ts file.

**Comment by mishushakov** [comment]
Good catch!
For now you might use try this:

https://codesandbox.io/p/sandbox/festive-leftpad-h8t3mj?file=%2Findex.ts%3A10%2C1
