### ISSUE TITLE
Make builtin types lazy

### ISSUE THREAD

**Issue by lorefnon** [stepci/garph#95]
So it is a bit strange that I can't create a type called Node when using garph because the library defines a type with the name. 

I understand that this goes against relay conventions, and I can use a different name, but ideally being a generic library, garph should not prevent me from doing something that graphql itself allows.  

I propose that we make the builtin types like nodeType, pageInfoType lazy so that they get defined if the consumer actually uses them.

```ts
  get nodeType() {
    this._nodeType ??= this.interface('Node', {
      id: this.id()
    })
    return this._nodeType
  }
```

**Comment by mishushakov** [comment]
With 9de43dd I have made it possible to overwrite built-in types

**Comment by lorefnon** [comment]
Ok, that's a simpler solution 👍🏾
